name: Generate Directory Tree

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate directory tree
        uses: jaywcjlove/github-action-folder-tree@main
        id: tree
        with:
          path: .
          exclude: ".git|node_modules"
          depth: 2

      - name: Commit TREE.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add TREE.md
          git commit -m "chore: auto-generate TREE.md" || echo "No changes to commit"
          git push
